language: python
python:
  - "3.5"
before_install:
  - mkdir -p $HOME/bin
  - wget https://github.com/github/git-lfs/releases/download/v1.3.0/git-lfs-linux-amd64-1.3.0.tar.gz
  - tar xvfz git-lfs-linux-amd64-1.3.0.tar.gz
  - mv git-lfs-1.3.0/git-lfs $HOME/bin/git-lfs
  - export PATH=$PATH:$HOME/bin/
install:
  - pip install -r requirements.txt
script: py.test
